///|
/// In this fn, we swap two rows (row_1 and row_2) or swap two columns (col_1 and col_2)
/// 
/// Parameters:
///
/// * 'matrix': The matrix you want to swap two columns or two rows.
/// * 'row_1' or 'col_1': The first row or column you want to swap.
/// * 'row_2' or 'col_2': The second row or column you want to swap.
///
/// Returns a new Matrix after swaping the two rows or columns.
///
/// Examples:
/// matrix = [
/// [1, 2, 3, 4]
/// [2, 3, 4, 5]
/// [3, 4, 5, 6]
/// ]
/// ```moonbit
